preprod_build:
    stage: build_preprod
    only:
        - tags
    except:
        - develop
    script:
        - export DEPLOY_ENV=preprod1
        - docker --debug build --build-arg proxy_name=${PROXY_NAME} --build-arg proxy_pass=${PROXY_PASS} --build-arg environment=${DEPLOY_ENV} --rm=true --cache-from ${registry_name} -f Dockerfile -t ${image_name} .
        - docker tag ${image_name} ${registry_name}/preprod:${version}
        - docker tag ${image_name} ${registry_name}/preprod:latest
        - docker push ${registry_name}/preprod:${version}
        - docker push ${registry_name}/preprod:latest
        - "if test ! -z \"$(docker images -q ${registry_name}/preprod)\"; then
                echo \"Images exist....deleting all associated images\";
                docker rmi $(docker images --format '{{.Repository}}:{{.Tag}}' | grep 'registry.gitlab.com/ebu/ebu-prepaid-skhokho') || true;
           fi"
        - docker rmi -f $(docker images -f \"dangling=true\" -q) || true

    when: manual

    tags:
        - fla_preprod_s03


preprod_traefik_deploy:
  stage: preprod_deploy
  only:
    - tags
  except:
    - develop
  script:
    - docker network create traefik -d overlay --attachable || true
    - docker stack rm mtn-preprod-ebu-prepaid || true
    - docker stack deploy -c ci/traefik-preprod.yml mtn-preprod-ebu-prepaid --with-registry-auth
  environment:
    name: traefik-preprod
    url: "https://portals-preprod.mtn.co.za/ebu-prepaid"
  when: manual
  tags:
    - fla_preprod_s01