dr1_build:
    stage: build_dr
    only:
        - tags
    except:
        - develop
    script:
        - export DEPLOY_ENV=dr1
        - docker --debug build --build-arg proxy_name=${PROXY_NAME} --build-arg proxy_pass=${PROXY_PASS} --build-arg environment=${DEPLOY_ENV} --rm=true --cache-from ${registry_name} -f Dockerfile -t ${image_name} .
        - docker tag ${image_name} ${registry_name}/dr/1:${version}
        - docker tag ${image_name} ${registry_name}/dr/1:latest
        - docker push ${registry_name}/dr/1:${version}
        - docker push ${registry_name}/dr/1:latest
        - "if test ! -z \"$(docker images -q ${registry_name}/dr/1)\"; then
                echo \"Images exist....deleting all associated images\";
                docker rmi $(docker images --format '{{.Repository}}:{{.Tag}}' | grep 'registry.gitlab.com/ebu/ebu-prepaid-skhokho') || true;
           fi"
        - docker rmi -f $(docker images -f "dangling=true" -q) || true
    when: manual
    tags:
        - fla_preprod_s03

dr1_deploy:
    stage: dr_deploy
    only:
        - tags
    except:
        - develop
    script:
        - docker network create ${network_name} || true
        - "if test ! -z \"$(docker images -q ${registry_name}/dr/1)\"; then
                docker rmi -f ${registry_name}/dr/1;
                docker rm -f ${image_name};
                docker run -d -p 8114:8114 --name=${image_name} --restart on-failure --net=${network_name}
                         --memory 8g --memory-swap 8g ${registry_name}/dr/1;
             else
                 docker run -d -p 8114:8114 --name=${image_name} --restart on-failure --net=${network_name}
                         --memory 8g --memory-swap 8g ${registry_name}/dr/1;
          fi"
        - docker rmi -f $(docker images -f \"dangling=true\" -q) || true;
    when: manual
    environment:
        name: ebu-prepaid_dr_1
        url: "https://flaolprvb08.mtn.co.za:8114/"
    tags:
        - fla_dr_b08

dr2_build:
    stage: build_dr
    only:
        - tags
    except:
        - develop
    script:
        - export DEPLOY_ENV=dr2
        - docker --debug build --build-arg proxy_name=${PROXY_NAME} --build-arg proxy_pass=${PROXY_PASS} --build-arg environment=${DEPLOY_ENV} --rm=true --cache-from ${registry_name} -f Dockerfile -t ${image_name} .
        - docker tag ${image_name} ${registry_name}/dr/2:${version}
        - docker tag ${image_name} ${registry_name}/dr/2:latest
        - docker push ${registry_name}/dr/2:${version}
        - docker push ${registry_name}/dr/2:latest
        - "if test ! -z \"$(docker images -q ${registry_name}/dr/2)\"; then
                echo \"Images exist....deleting all associated images\";
                docker rmi $(docker images --format '{{.Repository}}:{{.Tag}}' | grep 'registry.gitlab.com/ebu/ebu-prepaid-skhokho') || true;
           fi"
        - docker rmi -f $(docker images -f "dangling=true" -q) || true
    when: manual
    tags:
        - fla_preprod_s03

dr2_deploy:
    stage: dr_deploy
    only:
        - tags
    except:
        - develop
    script:
        - docker network create ${network_name} || true
        - "if test ! -z \"$(docker images -q ${registry_name}/dr/2)\"; then
                docker rmi -f ${registry_name}/dr/2;
                docker rm -f ${image_name};
                docker run -d -p 8114:8114 --name=${image_name} --restart on-failure --net=${network_name}
                         --memory 8g --memory-swap 8g ${registry_name}/dr/2;
             else
                 docker run -d -p 8114:8114 --name=${image_name} --restart on-failure --net=${network_name}
                         --memory 8g --memory-swap 8g ${registry_name}/dr/2;
          fi"
        - docker rmi -f $(docker images -f \"dangling=true\" -q) || true;
    when: manual
    environment:
        name: ebu-prepaid_dr_2
        url: "https://flaolprvb09.mtn.co.za:8114/"
    tags:
        - fla_dr_b09