version: "3.4"

services:
  ebu-prepaid:
    image: ${registry_name}/traefik_dev
    ports:
      - 8114:8114
    volumes:
      - certs-data:/home/docker_apps/dist/certs
    deploy:
      placement:
        constraints:
          - node.labels.PLACEMENT_GROUP==web-ui
      resources:
        limits:
          memory: 4g
      labels:
        - traefik.enable=true
        - traefik.http.routers.ebu-prepaid-https.entrypoints=websecure
        - traefik.http.routers.ebu-prepaid-https.rule=Host(`portals-dev.mtn.co.za`) && (PathPrefix(`/business/ebu-prepaid/`) || PathPrefix(`/business/ebu-prepaid/runtime`) || PathPrefix(`/business/ebu-prepaid/styles`) || PathPrefix(`/business/ebu-prepaid/polyfills`) || PathPrefix(`/business/ebu-prepaid/main`) || PathPrefix(`/business/ebu-prepaid/favicon`))
        - traefik.http.routers.ebu-prepaid-https.tls.certresolver=le
        - traefik.http.services.ebu-prepaid.loadbalancer.server.scheme=https
        - traefik.http.services.ebu-prepaid.loadbalancer.passhostheader=true
        - traefik.http.services.ebu-prepaid.loadbalancer.server.port=8114
        - traefik.docker.network=traefik
    networks:
      - traefik

volumes:
  certs-data:

networks:
  traefik:
    external:
      name: traefik
